# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=50)),
                ('grade_level', models.CharField(max_length=10)),
                ('align_id', models.IntegerField()),
            ],
        ),
    ]
