# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_lang', models.CharField(max_length=10)),
            ],
        ),
    ]
