# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0002_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='align_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='translation',
            name='grade_level',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='translation',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='translation',
            name='text',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='trans_text',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
    ]
